version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis-queue
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  api-server:
    build: .
    container_name: api-server
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=production
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs

  worker:
    build: .
    container_name: queue-worker
    command: npm run worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=production
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs

volumes:
  redis_data:
